[
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/340067078",
    "html_url": "https://github.com/expressjs/express/issues/3461#issuecomment-340067078",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/3461",
    "id": 340067078,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0MDA2NzA3OA==",
    "user": {
      "login": "dougwilson",
      "id": 67512,
      "node_id": "MDQ6VXNlcjY3NTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/67512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dougwilson",
      "html_url": "https://github.com/dougwilson",
      "followers_url": "https://api.github.com/users/dougwilson/followers",
      "following_url": "https://api.github.com/users/dougwilson/following{/other_user}",
      "gists_url": "https://api.github.com/users/dougwilson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dougwilson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dougwilson/subscriptions",
      "organizations_url": "https://api.github.com/users/dougwilson/orgs",
      "repos_url": "https://api.github.com/users/dougwilson/repos",
      "events_url": "https://api.github.com/users/dougwilson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dougwilson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-10-27T19:41:46Z",
    "updated_at": "2017-10-27T19:41:46Z",
    "author_association": "MEMBER",
    "body": "I use arrow functions with Express.js all the time, and a simple test of your example works. Can you provide a full program that reproduces the issue? May want to also put the versions you're using like Express.js version, Node.js version, etc. and also the contents of your `Error` template file and what templating engine module you're using.",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/340067078/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/340069212",
    "html_url": "https://github.com/expressjs/express/issues/3461#issuecomment-340069212",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/3461",
    "id": 340069212,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0MDA2OTIxMg==",
    "user": {
      "login": "caub",
      "id": 3134574,
      "node_id": "MDQ6VXNlcjMxMzQ1NzQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3134574?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/caub",
      "html_url": "https://github.com/caub",
      "followers_url": "https://api.github.com/users/caub/followers",
      "following_url": "https://api.github.com/users/caub/following{/other_user}",
      "gists_url": "https://api.github.com/users/caub/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/caub/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/caub/subscriptions",
      "organizations_url": "https://api.github.com/users/caub/orgs",
      "repos_url": "https://api.github.com/users/caub/repos",
      "events_url": "https://api.github.com/users/caub/events{/privacy}",
      "received_events_url": "https://api.github.com/users/caub/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-10-27T19:50:50Z",
    "updated_at": "2017-10-27T19:52:57Z",
    "author_association": "NONE",
    "body": "Sorry 1e3 times dougwilson\r\n\r\nso the error was elsewhere, and I got confused while testing\r\n\r\nthe problem seems that extending Error can give some weird behavior with .message\r\n\r\nedit: oh I guess `.message` is a getter\r\n\r\n```js\r\napp.use((req, res, next) => {\r\n\tconst error = new HttpError({status: 404, message: `{${req.url}} not found`});\r\n\tres.status(error.status);\r\n\tres.render('Error', error); // here message won't appear in the view\r\n\t// res.render('Error', {message: error.message}); // this works, surprisingly\r\n});\r\n```\r\n\r\n```js\r\nmodule.exports = class HttpError extends Error {\r\n\tconstructor(data='Server error', status){\r\n\t\tconst e = typeof data === 'string' ? {message: data} : data;\r\n\t\tsuper(e.message);\r\n\t\tthis.status = status || e.status || 400;\r\n\t\tthis.errors = e.errors;\r\n\t}\r\n\r\n\ttoString() {\r\n\t\treturn this.message;\r\n\t}\r\n\r\n\ttoJSON() {\r\n\t\treturn {\r\n\t\t\tmessage: this.message,\r\n\t\t\terrors: this.errors\r\n\t\t};\r\n\t}\r\n};\r\n```\r\n```js\r\n// view engine:\r\nexports.reactEngine = function reactEngine(filePath, options, callback) {\r\n\tconst component = require(filePath);\r\n\tconst markup = renderToStaticMarkup(createElement(component, options));\r\n\tconsole.log(options, markup);\r\n\tcallback(null, markup);\r\n};\r\n```\r\n\r\nI can close the issue, sorry again",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/340069212/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]