[
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/14969203",
    "html_url": "https://github.com/expressjs/express/issues/1543#issuecomment-14969203",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/1543",
    "id": 14969203,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0OTY5MjAz",
    "user": {
      "login": "igl",
      "id": 293519,
      "node_id": "MDQ6VXNlcjI5MzUxOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/293519?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/igl",
      "html_url": "https://github.com/igl",
      "followers_url": "https://api.github.com/users/igl/followers",
      "following_url": "https://api.github.com/users/igl/following{/other_user}",
      "gists_url": "https://api.github.com/users/igl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/igl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/igl/subscriptions",
      "organizations_url": "https://api.github.com/users/igl/orgs",
      "repos_url": "https://api.github.com/users/igl/repos",
      "events_url": "https://api.github.com/users/igl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/igl/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-03-15T16:04:16Z",
    "updated_at": "2013-03-15T16:04:16Z",
    "author_association": "NONE",
    "body": "You probably res.render() / res.end() twice. Async f'up?\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/14969203/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/14999566",
    "html_url": "https://github.com/expressjs/express/issues/1543#issuecomment-14999566",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/1543",
    "id": 14999566,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0OTk5NTY2",
    "user": {
      "login": "tj",
      "id": 25254,
      "node_id": "MDQ6VXNlcjI1MjU0",
      "avatar_url": "https://avatars.githubusercontent.com/u/25254?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tj",
      "html_url": "https://github.com/tj",
      "followers_url": "https://api.github.com/users/tj/followers",
      "following_url": "https://api.github.com/users/tj/following{/other_user}",
      "gists_url": "https://api.github.com/users/tj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tj/subscriptions",
      "organizations_url": "https://api.github.com/users/tj/orgs",
      "repos_url": "https://api.github.com/users/tj/repos",
      "events_url": "https://api.github.com/users/tj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tj/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-03-16T04:53:23Z",
    "updated_at": "2013-03-16T04:53:23Z",
    "author_association": "MEMBER",
    "body": "yeah this is typically a user error doing something weird replying twice by accident, express and connect stuff should be fine\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/14999566/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/15100492",
    "html_url": "https://github.com/expressjs/express/issues/1543#issuecomment-15100492",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/1543",
    "id": 15100492,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE1MTAwNDky",
    "user": {
      "login": "akamensky",
      "id": 985805,
      "node_id": "MDQ6VXNlcjk4NTgwNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/985805?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/akamensky",
      "html_url": "https://github.com/akamensky",
      "followers_url": "https://api.github.com/users/akamensky/followers",
      "following_url": "https://api.github.com/users/akamensky/following{/other_user}",
      "gists_url": "https://api.github.com/users/akamensky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/akamensky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/akamensky/subscriptions",
      "organizations_url": "https://api.github.com/users/akamensky/orgs",
      "repos_url": "https://api.github.com/users/akamensky/repos",
      "events_url": "https://api.github.com/users/akamensky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/akamensky/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-03-19T07:19:20Z",
    "updated_at": "2013-03-19T07:19:20Z",
    "author_association": "NONE",
    "body": "That's weird that this issue is closed without any consideration.\n\nTo answer question - no, we are not using async and keep all methods as simple as possible, but it is happening anyway.\n\nMost strange to me is that this happens very randomly. So one time request can work fine, next time it will crash the app, after this it can work again for several times and then crash it for several times in a row. I could not see any pattern it how this issue appears though me and other devs checked our code many times.\n\nBTW, this started happening after update of node.js. Now we are on v0.10.0 and with this version also node-inspector stopped working with the same kind of bug:\n\n```\n19 Mar 15:02:45 - [nodev node-inspector] http.js:708\n19 Mar 15:02:45 - [nodev node-inspector]     throw new Error('Can\\'t set headers after they are sent.');\n19 Mar 15:02:45 - [nodev node-inspector]           ^\n19 Mar 15:02:45 - [nodev node-inspector] Error: Can't set headers after they are sent.\n19 Mar 15:02:45 - [nodev node-inspector]     at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)\n19 Mar 15:02:45 - [nodev node-inspector]     at ServerResponse.res.setHeader (/usr/lib/node_modules/node-inspector/node_modules/connect/lib/patch.js:62:20)\n19 Mar 15:02:45 - [nodev node-inspector]     at /usr/lib/node_modules/node-inspector/node_modules/connect/lib/middleware/static.js:168:11\n19 Mar 15:02:45 - [nodev node-inspector]     at Object.oncomplete (fs.js:93:15)\n```\n\nSo it possibly could be related to some changes in node.js.\nI will try to roll back to older version and see if it still will be happening.\n\nBut still closing bugs without any consideration isn't the best way i believe.\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/15100492/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/expressjs/express/issues/comments/16335895",
    "html_url": "https://github.com/expressjs/express/issues/1543#issuecomment-16335895",
    "issue_url": "https://api.github.com/repos/expressjs/express/issues/1543",
    "id": 16335895,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE2MzM1ODk1",
    "user": {
      "login": "tj",
      "id": 25254,
      "node_id": "MDQ6VXNlcjI1MjU0",
      "avatar_url": "https://avatars.githubusercontent.com/u/25254?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tj",
      "html_url": "https://github.com/tj",
      "followers_url": "https://api.github.com/users/tj/followers",
      "following_url": "https://api.github.com/users/tj/following{/other_user}",
      "gists_url": "https://api.github.com/users/tj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tj/subscriptions",
      "organizations_url": "https://api.github.com/users/tj/orgs",
      "repos_url": "https://api.github.com/users/tj/repos",
      "events_url": "https://api.github.com/users/tj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tj/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-04-13T16:18:46Z",
    "updated_at": "2013-04-13T16:18:46Z",
    "author_association": "MEMBER",
    "body": "I've never once seen this where it was not a user error, without more information there's nothing we can do to look into it\n",
    "reactions": {
      "url": "https://api.github.com/repos/expressjs/express/issues/comments/16335895/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]