[
  {
    "url": "https://api.github.com/repos/lodash/lodash/issues/comments/513066279",
    "html_url": "https://github.com/lodash/lodash/issues/4377#issuecomment-513066279",
    "issue_url": "https://api.github.com/repos/lodash/lodash/issues/4377",
    "id": 513066279,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxMzA2NjI3OQ==",
    "user": {
      "login": "jdalton",
      "id": 4303,
      "node_id": "MDQ6VXNlcjQzMDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4303?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdalton",
      "html_url": "https://github.com/jdalton",
      "followers_url": "https://api.github.com/users/jdalton/followers",
      "following_url": "https://api.github.com/users/jdalton/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdalton/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdalton/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdalton/subscriptions",
      "organizations_url": "https://api.github.com/users/jdalton/orgs",
      "repos_url": "https://api.github.com/users/jdalton/repos",
      "events_url": "https://api.github.com/users/jdalton/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdalton/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-07-19T02:32:12Z",
    "updated_at": "2019-07-19T02:32:12Z",
    "author_association": "MEMBER",
    "body": "Thanks @stephaniewilkinson!\r\n\r\nI bumped the packages to remove the unintentionally added helpers.",
    "reactions": {
      "url": "https://api.github.com/repos/lodash/lodash/issues/comments/513066279/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/lodash/lodash/issues/comments/513068807",
    "html_url": "https://github.com/lodash/lodash/issues/4377#issuecomment-513068807",
    "issue_url": "https://api.github.com/repos/lodash/lodash/issues/4377",
    "id": 513068807,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxMzA2ODgwNw==",
    "user": {
      "login": "stephaniewilkinson",
      "id": 2397260,
      "node_id": "MDQ6VXNlcjIzOTcyNjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2397260?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stephaniewilkinson",
      "html_url": "https://github.com/stephaniewilkinson",
      "followers_url": "https://api.github.com/users/stephaniewilkinson/followers",
      "following_url": "https://api.github.com/users/stephaniewilkinson/following{/other_user}",
      "gists_url": "https://api.github.com/users/stephaniewilkinson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stephaniewilkinson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stephaniewilkinson/subscriptions",
      "organizations_url": "https://api.github.com/users/stephaniewilkinson/orgs",
      "repos_url": "https://api.github.com/users/stephaniewilkinson/repos",
      "events_url": "https://api.github.com/users/stephaniewilkinson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stephaniewilkinson/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-07-19T02:45:24Z",
    "updated_at": "2019-07-19T02:45:24Z",
    "author_association": "NONE",
    "body": "Fantastic! Thanks for the quick response. I'll try again.",
    "reactions": {
      "url": "https://api.github.com/repos/lodash/lodash/issues/comments/513068807/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/lodash/lodash/issues/comments/514318037",
    "html_url": "https://github.com/lodash/lodash/issues/4377#issuecomment-514318037",
    "issue_url": "https://api.github.com/repos/lodash/lodash/issues/4377",
    "id": 514318037,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxNDMxODAzNw==",
    "user": {
      "login": "nateperry",
      "id": 3438407,
      "node_id": "MDQ6VXNlcjM0Mzg0MDc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3438407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nateperry",
      "html_url": "https://github.com/nateperry",
      "followers_url": "https://api.github.com/users/nateperry/followers",
      "following_url": "https://api.github.com/users/nateperry/following{/other_user}",
      "gists_url": "https://api.github.com/users/nateperry/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nateperry/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nateperry/subscriptions",
      "organizations_url": "https://api.github.com/users/nateperry/orgs",
      "repos_url": "https://api.github.com/users/nateperry/repos",
      "events_url": "https://api.github.com/users/nateperry/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nateperry/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-07-23T17:58:26Z",
    "updated_at": "2019-07-23T17:58:26Z",
    "author_association": "NONE",
    "body": "I too have been having this exact issue. @jdalton can you give a little more context to what happened and what the solution was? I understand that a later version fixed this, just trying to get a better sense of what it was.",
    "reactions": {
      "url": "https://api.github.com/repos/lodash/lodash/issues/comments/514318037/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/lodash/lodash/issues/comments/514335305",
    "html_url": "https://github.com/lodash/lodash/issues/4377#issuecomment-514335305",
    "issue_url": "https://api.github.com/repos/lodash/lodash/issues/4377",
    "id": 514335305,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxNDMzNTMwNQ==",
    "user": {
      "login": "jdalton",
      "id": 4303,
      "node_id": "MDQ6VXNlcjQzMDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4303?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdalton",
      "html_url": "https://github.com/jdalton",
      "followers_url": "https://api.github.com/users/jdalton/followers",
      "following_url": "https://api.github.com/users/jdalton/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdalton/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdalton/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdalton/subscriptions",
      "organizations_url": "https://api.github.com/users/jdalton/orgs",
      "repos_url": "https://api.github.com/users/jdalton/repos",
      "events_url": "https://api.github.com/users/jdalton/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdalton/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-07-23T18:46:37Z",
    "updated_at": "2019-07-23T18:46:58Z",
    "author_association": "MEMBER",
    "body": "This has been resolved with the `lodash` package collection (`lodash`, `lodash-amd`, and `lodash-es`) update to `4.17.15`. The problem was package-organization/repo-tag helper scripts I use accidentally got added to the npm publish packages. Updating your dep will resolve the issue.",
    "reactions": {
      "url": "https://api.github.com/repos/lodash/lodash/issues/comments/514335305/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/lodash/lodash/issues/comments/514343210",
    "html_url": "https://github.com/lodash/lodash/issues/4377#issuecomment-514343210",
    "issue_url": "https://api.github.com/repos/lodash/lodash/issues/4377",
    "id": 514343210,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUxNDM0MzIxMA==",
    "user": {
      "login": "nateperry",
      "id": 3438407,
      "node_id": "MDQ6VXNlcjM0Mzg0MDc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3438407?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nateperry",
      "html_url": "https://github.com/nateperry",
      "followers_url": "https://api.github.com/users/nateperry/followers",
      "following_url": "https://api.github.com/users/nateperry/following{/other_user}",
      "gists_url": "https://api.github.com/users/nateperry/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nateperry/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nateperry/subscriptions",
      "organizations_url": "https://api.github.com/users/nateperry/orgs",
      "repos_url": "https://api.github.com/users/nateperry/repos",
      "events_url": "https://api.github.com/users/nateperry/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nateperry/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-07-23T19:09:20Z",
    "updated_at": "2019-07-23T19:09:20Z",
    "author_association": "NONE",
    "body": "Thanks for the details! I can confirm that I am no longer seeing this error.",
    "reactions": {
      "url": "https://api.github.com/repos/lodash/lodash/issues/comments/514343210/reactions",
      "total_count": 1,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 1,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]